### ISSUE TITLE
Display not printing help

### ISSUE THREAD

**Issue by burrowss** [Accelegator/accelegator#57]
When the help command is typed it, nothing is printed. It should be printing the types of commands the user should enter.

**Comment by ZachAndrews98** [comment]
The reason for this is in parse_arguments there is no "help" information assigned for each argument, I can take care of that.

**Comment by delgrecoj** [comment]
`repl.py`, the last two cases should be for `7` and `8`... broke during refactoring of the REPL, apparently.

(answered both of these bug issues because they are regressions from refactoring work done after the handoff that we weren't expecting)

(also, @ZachAndrews98 that's not the problem; `parse_arguments` isn't responsible for that in the way you're thinking it is; see the above fix.)

**Comment by burrowss** [comment]
@delgrecoj That was the issue. Thanks again
